-- Bind every guest access token to one revocable identity generation. The
-- stable GuestIdentity id can be reused after voluntary logout, while this
-- session changes on every authorized join so old tokens never revive.
ALTER TABLE "GuestIdentity" ADD COLUMN "sessionId" TEXT;

-- Give existing rows a deterministic non-null generation. Legacy guest JWTs
-- lack this claim and are intentionally rejected; the next authorized join
-- replaces this value with a fresh random UUID generated by the API.
UPDATE "GuestIdentity" SET "sessionId" = "id" WHERE "sessionId" IS NULL;

ALTER TABLE "GuestIdentity" ALTER COLUMN "sessionId" SET NOT NULL;
